# Look at the optimzation progress for DYCORS
David Eriksson <dme65@cornell.edu>

In [8]:
from pySOT.experimental_design import SymmetricLatinHypercube
from pySOT.strategy import DYCORSStrategy
from pySOT.surrogate import RBFInterpolant, CubicKernel, LinearTail
from pySOT.optimization_problems import Func3C,Func3I,Func2C,Func2R,Ackley15C,Ackley15I
from pySOT.utils import progress_plot
from poap_read.controller import ThreadController, SerialController, BasicWorkerThread
import numpy as np

import matplotlib.pylab as plt
plt.rc('xtick', labelsize=16) 
plt.rc('ytick', labelsize=16)

In [9]:
num_threads = 4
max_evals = 200
num_runs = 1

func = Func2R(dim=4)
print(func.info)

rbf = RBFInterpolant(
    dim=func.dim, lb=func.lb, ub=func.ub, kernel=CubicKernel(), tail=LinearTail(func.dim))
slhd = SymmetricLatinHypercube(dim=func.dim, num_pts=2*(func.dim+1))

4-dimensional Func2C function 
Global optimum: f(1, 1, -0.0898/2, 0.7126/2) = -0.2063


## Run in serial

In [3]:
results_serial = np.zeros((max_evals, num_runs))
for i in range(num_runs):
    controller = SerialController(objective=func.eval)
    controller.strategy = DYCORSStrategy(
        max_evals=max_evals, opt_prob=func, asynchronous=False, 
        exp_design=slhd, surrogate=rbf, num_cand=100*func.dim,
        batch_size=1)

    result = controller.run()
    results_serial[:, i] = np.array(
        [o.value for o in controller.fevals if o.value is not None])

[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
expand
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
[0, 1, 2]
[0, 1, 2, 3, 4]
shrink The rank has changed
[1, 0, 2]
[0, 3, 4, 1, 2]
[1, 0, 2]
[0, 3, 4, 1, 2]
[1, 0, 2]
[0, 3, 4, 1, 2]
[1, 0, 2]
[0, 3, 4, 1, 2]
shrink The rank has changed
[2, 1, 0]
[2, 4, 0, 3, 1]
[2, 1, 0]
[2, 4, 0, 3, 1]
[2, 1, 0]
[2, 4, 0, 3, 1]
[2, 1, 0]
[2, 4, 0, 3, 1]
shrink The rank has changed
[0, 2, 1]
[1, 4, 3, 2, 0]
[0, 2, 1]
[1, 4, 3, 2, 0]
[0, 2, 1]
[1, 4, 3, 2, 0]
[0, 2, 1]
[1, 4, 3, 2, 0]
shrink The rank has changed
[0, 1, 2]
[2, 0, 1, 3, 4]
[0, 1, 2]
[2, 0, 1, 3, 4]
[0, 1, 2]
[2, 0, 1, 3, 4]
expand
[0, 1, 2]
[2, 0, 1, 3, 4]
[0, 1, 2]
[2, 0, 1, 3, 4]
[0, 1, 2]
[2, 0, 1, 3, 4]
[0, 1, 2]
[2, 0,

In [4]:
record = controller.best_point()

In [5]:
record.params

(array([ 2.        ,  0.        , -0.01079262,  0.35797724]),)

In [6]:
controller.best_loc()

[ 2.          0.         -0.01079262  0.35797724]


array([ 1.        ,  1.        , -0.01079262,  0.35797724])

In [7]:
record.value

-0.20259124460113845

In [ ]:
func2 = Func2I(dim=4)
print(func.info)

rbf = RBFInterpolant(
    dim=func2.dim, lb=func2.lb, ub=func2.ub, kernel=CubicKernel(), tail=LinearTail(func2.dim))
slhd = SymmetricLatinHypercube(dim=func2.dim, num_pts=2*(func2.dim+1))

results_serial2 = np.zeros((max_evals, num_runs))
for i in range(num_runs):
    controller = SerialController(objective=func.eval)
    controller.strategy = DYCORSStrategy(
        max_evals=max_evals, opt_prob=func2, asynchronous=False, 
        exp_design=slhd, surrogate=rbf, num_cand=100*func2.dim,
        batch_size=1)

    result2 = controller.run()
    results_serial2[:, i] = np.array(
        [o.value for o in controller.fevals if o.value is not None])

In [ ]:
file_path = 'D:/pySOT-master/data/Func2C.txt'
with open(file_path, 'r') as file:
    data = [float(line.strip()) for line in file.readlines()]
arr = np.array(data)
results_casmopolitan = arr.reshape(10, 200).T

file_path = 'D:/pySOT-master/data/Func2C_ran.txt'
with open(file_path, 'r') as file:
    data = [float(line.strip()) for line in file.readlines()]
arr = np.array(data)
results_random = arr.reshape(10, 200).T

## Compare the results

In [ ]:
plt.figure(figsize=(15, 8))
fvals1 = np.minimum.accumulate(results_serial)
plt.errorbar(np.arange(max_evals)+1, y=np.mean(fvals1, axis=1), 
                yerr=np.std(fvals1, axis=1)/np.sqrt(float(num_runs)))
#     plt.plot(np.arange(0, fvals.shape[0]), np.minimum.accumulate(fvals), lw=2)
fvals4 = np.minimum.accumulate(results_serial2)
plt.errorbar(np.arange(max_evals)+1, y=np.mean(fvals4, axis=1), 
                yerr=np.std(fvals4, axis=1)/np.sqrt(float(num_runs)))
plt.ylabel("Best value found so far", fontsize=16)
plt.xlabel("Evaluations", fontsize=16)

fvals2 = np.minimum.accumulate(results_casmopolitan)
plt.errorbar(np.arange(200)+1, y=np.mean(fvals2, axis=1), 
                yerr=np.std(fvals2, axis=1)/np.sqrt(float(10)))

fvals3 = np.minimum.accumulate(results_random)
plt.errorbar(np.arange(200)+1, y=np.mean(fvals3, axis=1), 
                yerr=np.std(fvals3, axis=1)/np.sqrt(float(10)))
plt.ylim([-0.23,0.2])
plt.legend(("Serial","Serial_int","casmopolitan","random"), fontsize=16)
plt.title("Func2C")
plt.show()

## Run asynchronously

In [ ]:
results_async = np.zeros((max_evals, num_runs))
for i in range(num_runs):
    controller = ThreadController()
    controller.strategy = DYCORSStrategy(
        max_evals=max_evals, opt_prob=ackley, asynchronous=True, 
        exp_design=slhd, surrogate=rbf, num_cand=100*ackley.dim)

    for _ in range(num_threads):
        worker = BasicWorkerThread(controller, ackley.eval)
        controller.launch_worker(worker)

    result = controller.run()
    results_async[:, i] = np.array(
        [o.value for o in controller.fevals if o.value is not None])

## Run synchronously

In [ ]:
results_sync = np.zeros((max_evals, num_runs))
for i in range(num_runs):
    controller = ThreadController()
    controller.strategy = DYCORSStrategy(
        max_evals=max_evals, opt_prob=ackley, asynchronous=False, 
        exp_design=slhd, surrogate=rbf, num_cand=100*ackley.dim,
        batch_size=num_threads)

    for _ in range(num_threads):
        worker = BasicWorkerThread(controller, ackley.eval)
        controller.launch_worker(worker)

    result = controller.run()
    results_sync[:, i] = np.array(
        [o.value for o in controller.fevals if o.value is not None])

In [ ]:
ranks = [[0,1,2],[0,1,2,3,4]]
ranks[1] = np.random.permutation(ranks[1])
ranks